services:
  agents:
    image: lachsbagel/moragents_dockers-agents:amd64-0.2.2
    build:
      dockerfile: Dockerfile
      context: ./agents
    ports:
      - "8080:5000"
    restart: always
    volumes:
      - agents_data:/var/lib/agents
      - ./agents/src:/app/src
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - app-network

  nginx:
    image: lachsbagel/moragents_dockers-nginx:amd64-0.2.2
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: nginx
    depends_on:
      - agents
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${SSL_PORT:-443}:443"
    volumes:
      - ./frontend/.env:/usr/share/nginx/html/.env
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  agents_data: