services:
  agents:
    image: zico_agents
    build:
      dockerfile: Dockerfile
      context: ./agents
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - agents_data:/var/lib/agents
      - ./agents/src:/app/src
      - ./agents/ssl:/app/ssl:ro
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - app-network

volumes:
  agents_data:

networks:
  app-network:
    driver: bridge