services:
  agents:
    image: lachsbagel/moragents_dockers-agents:amd64-0.2.2
    build:
      dockerfile: Dockerfile
      context: ./agents
    ports:
      - "8080:5000"
      - "8443:5443"
    restart: always
    volumes:
      - agents_data:/var/lib/agents
      - ./agents/src:/app/src
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - app-network

  nginx:
    image: lachsbagel/moragents_dockers-nginx:amd64-0.2.2
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: nginx
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - agents
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${SSL_PORT:-443}:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/nginx/certs:ro
    env_file:
      - .env
    networks:
      - app-network

volumes:
  agents_data:

networks:
  app-network:
    driver: bridge